twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        appName: '%app.name%'
        appVersion: '%app.version%'
        tokenTTL: '%tokenTTL%'
    paths:
        '%kernel.project_dir%/public/css': styles

when@test:
    twig:
        strict_variables: true
